#-----------------------------------------------------------#
#                     ABOUT THIS PLUGIN                     #
#-----------------------------------------------------------#

# Guilds by the Glare Masters
# Guilds on DevBukkit: https://dev.bukkit.org/projects/the-guilds-plugin
# Guilds on SpigotMC: https://www.spigotmc.org/resources/guilds.48920/
# Guilds on GitHub: https://github.com/darbyjack/Guilds-Plugin
# Guilds Wiki: https://glaremasters.me/wiki/
# Guilds Development Builds: https://ci.glaremasters.me/job/Guilds/

#-----------------------------------------------------------#
#                     IMPORTANT INFORMATION                 #
#-----------------------------------------------------------#

# This is used to determine what version of the config you are using.
# Please do not change this as it may cause issues with your config.
version: 1

# This will automatically move your current config to "config-old.yml" and replace with a new, updated, "config.yml".
# If you ever get tired of your config being moved, just change this to "false".
auto-update-config: true

# This is used for the Guild's Announcement System, which allow me (The Author) to communicate to you guys without updating.
# The way this works is very simple. If you have "console" set to "true", you will see the announcement when the server starts.
# If you have "in-game" set to "true", your OPed players will see it the first time they login to the server.
# OPed players will only be notified on the first time they login after each server reboot.
announcements:
  console: true
  in-game: true

#-----------------------------------------------------------#
#                     CHOOSE YOUR LANGUAGE                  #
#-----------------------------------------------------------#

# Choosing your language for the plugin couldn't be easier! The default language is english.
# Not an english server? No worries, you can choose from the following list of languages that we currently support.
# If you speak another language but don't see it here, feel free to submit it via one of the links above to have it added to the plugin.
# NOTE: If you change your language please ONLY use from the list above and use them EXACTLY as they are spelled in the list above.
# Example: If I am a french server, I would change lang: english to lang: french
# If you try and use a different language than any in the list above, the plugin will not function in a normal manner.
lang: en-US


# DO NOT TOUCH THIS PLEASE

supported-languages:
- en-US
- fr-FR

# This section is for event handler that I feel should be optional for you guys.
main-hooks:
  essentials-chat: false
  tablist-guilds: false
  worldguard-claims: false


#-----------------------------------------------------------#
#              Rewards / Tickets Configuration              #
#-----------------------------------------------------------#

# This part of the config will allow you to configure what different rewards will look like inside the plugin.
# Keep in mind, this is for stuff like voting or crate plugin rewards.
# Console will be able to run the /guild give on a player to give different items.
# This may throw errors if you are on 1.8

upgrade-ticket:
  name: "&bGuild Upgrade Ticket"
  lore: "&dRight click this ticket to upgrade your guild tier!"
  material: "PAPER"


  #-----------------------------------------------------------#
  #                     GUI CONFIGURATION                     #
  #-----------------------------------------------------------#

  # In this section of the config you can choose if you would look a GUI for various commands. The ones displayed below are the only ones that have implemented GUIs on them.
  # As stated above, the name here such as list and info will modify data inside that commands GUI.
  # If your server's language is not english, you will need to manually modify these to your server's language and they will display in the GUI as your new input.

  # The "list" section allows you to choose how the /guild list is styled.
  # You can change the colors, and the language of all parts of the guild list GUI.
  # The item is what is used to display all the guilds.

guild-list:
  gui-name: "Guild List"
  item-name: "{player}'s Guild"
  next-page-item: "EMPTY_MAP"
  next-page-item-name: "Next Page"
  previous-page-item: "EMPTY_MAP"
  previous-page-item-name: "Previous Page"
  page-number-item: "DIAMOND_BLOCK"
  page-number-item-name: "Page: {page}"
  head-lore:
  - "Name: {guild-name}"
  - "Prefix: {guild-prefix}"
  - "Master: {guild-master}"
  - "Status: {guild-status}"
  - "Tier: {guild-tier}"
  - "Balance: {guild-balance}"
  - "Member Count: {guild-member-count}"

# You can choose what random items are used to display Guilds in the Guild List
random-items:
- "STICK"
- "DIAMOND_SPADE"
- "REDSTONE_TORCH_ON"
- "DIAMOND_BLOCK"

# The "info" section allows you to choose how information in /guild info is displayed to users.
# You can change the colors, and the language of all parts of the guild info GUI.
info:
  balance: "&bBank Balance: &c{guild-balance}"
  deaths: "&bDeaths: &c{deaths}"
  guildname: "&bGuild: &c{guild-name}"
  guildstatus: "&bStatus: &c{guild-status}"
  guildtier: "&bTier: &c{guild-tier}"
  info: "Information: "
  kills: "&bKills: &c{kills}"
  master: "&bMaster: &c{guild-master}"
  max-balance: "&bMax Balance: &c{guild-max-balance}"
  member-count: "&bMember Count: &c{member-count}"
  money: "Money: "
  playername: "&bName: &c{player-name}"
  prefix: "&bPrefix: &c{guild-prefix}"
  role: "&bRole: &c{guild-role}"

# This part controls what is shown as the inventory name for things such as Guild List and Guild Vaults.
gui-name:
  vault: "Guild Vault"
  info: "Guild Info"
  buff: "Guild Buffs"
# head-name is what show's when you hover over a head in the Guild List. For example, the default will show Username's Guild

#-----------------------------------------------------------#
#                     Buff Configuration                    #
#-----------------------------------------------------------#

# In this section of the config, you can modify the buff name, price, time, and amplifier (Haste 1, 2 ,3 4, etc).
# The current will give Haste 2, Speed 2, etc with "1". If you make it "2", it'll change it to 3, and so on.

# Do you want disable the ability to buy multiple buffs at once?
disable-buff-stacking: true

# Do you want to use a guild's bank balance for buying the buffs?
use-guild-bank: false

# In this section you can modify the name of all the buffs, allowing you to have cool, custom names!
# The price is all in a dollar amount.
# The time is in seconds, so , haste: 60 is seconds.
buff:
  name:
    haste: "Substance of the Redmod Graff"
    speed: "Blessing of the Cheetah"
    fire-resistance: "Scales of the Dragon"
    night-vision: "Eyes of the Lurking Demon"
    invisibility: "Feet of the Ghostly Walker"
    strength: "Mighty Strength of the Pouncing Lion"
    jump: "Bounce of the Quick Witted Rabbit"
    water-breathing: "Lungs of the Albino Shark"
    regeneration: "Integrity of the Mystic Witch"
  price:
    haste: 60
    speed: 60
    fire-resistance: 60
    night-vision: 60
    invisibility: 60
    strength: 60
    jump: 60
    water-breathing: 60
    regeneration: 60
  time:
    haste: 60
    speed: 60
    fire-resistance: 60
    night-vision: 60
    invisibility: 60
    strength: 60
    jump: 60
    water-breathing: 60
    regeneration: 60
  amplifier:
    haste: 1
    speed: 1
    fire-resistance: 1
    night-vision: 1
    invisibility: 1
    strength: 1
    jump: 1
    water-breathing: 1
    regeneration: 1
  icon:
    haste: "FEATHER"
    speed: "SUGAR"
    fire-resistance: "BLAZE_POWDER"
    night-vision: "REDSTONE_TORCH_ON"
    invisibility: "EYE_OF_ENDER"
    strength: "DIAMOND_SWORD"
    jump: "DIAMOND_BOOTS"
    water-breathing: "BUCKET"
    regeneration: "EMERALD"
  description:
    price: "&bPrice: "
    length: "&bLength of Buff: "
    haste:
    - "&bThis buff will allow you and your"
    - "&bGuild Members to obtain increased"
    - "&bmining speed for a certain amount of time."
    speed:
    - "&bThis buff will allow you and your"
    - "&bGuild Members to obtain increased"
    - "&bmovement speed for a certain amount of time."
    fire-resistance:
    - "&bThis buff will allow you and your"
    - "&bGuild Members to obtain increased"
    - "&bfire resistance for a certain amount of time."
    night-vision:
    - "&bThis buff will allow you and your"
    - "&bGuild Members to obtain increased"
    - "&bnight vision for a certain amount of time."
    invisibility:
    - "&bThis buff will allow you and your"
    - "&bGuild Members to obtain increased"
    - "&binvisibility for a certain amount of time."
    strength:
    - "&bThis buff will allow you and your"
    - "&bGuild Members to obtain increased"
    - "&bstrength for a certain amount of time."
    jump:
    - "&bThis buff will allow you and your"
    - "&bGuild Members to obtain increased"
    - "&bjump for a certain amount of time."
    water-breathing:
    - "&bThis buff will allow you and your"
    - "&bGuild Members to obtain increased"
    - "&bwater-breathing for a certain amount of time."
    regeneration:
    - "&bThis buff will allow you and your"
    - "&bGuild Members to obtain increased"
    - "&bregeneration for a certain amount of time."
  display:
    haste: true
    speed: true
    fire-resistance: true
    night-vision: true
    invisibility: true
    strength: true
    jump: true
    water-breathing: true
    regeneration: true


#-----------------------------------------------------------#
#                     Vault Configuration                   #
#-----------------------------------------------------------#
# Currently not working in the latest release, working on a fix
cost:
  creation: 0
  sethome: 0

#-----------------------------------------------------------#
#                  Guild Claims Configuration               #
#-----------------------------------------------------------#
# This section of the config will allow you to handle guild land claiming.
# Remember that the enable / disable for this is the WorldGuard Hook at the TOP of the config.
# There are multiple options when it comes to guild claims. For the time being, all guilds will only get one claim.
# As a server owner, you will have a few options here.
# First off, you will have the ability to have a standard set claim size.
# There is an option you can modify if you want players to be able to set their own claim size.
# Don't worry, you will be able to modify the max claim size to prevent abuse.

# This is the number of blocks around the player it will try to create the region
# Keep in mind this is the RADIUS, it will go this many blocks in both directions
# For example, if you take the default 15, it'll do 30 total as it will go
# 15 blocks in both directions
# This is a CUBOID region, not SPHERE
claim-radius: 15

# Customize the entrance and exit message of joining claims
# Supports {prefix} for guild prefix and {guild} for guild name
# Also supports color codes!
claim-enter-message: "&aNow entering &d{guild}'s &aclaim!"
claim-exit-message: "&aNow leaving &d{guild}'s &aclaim!"

# Would you like to disable guild claiming in specific worlds?
disabled-worlds:
  -

#-----------------------------------------------------------#
#                     Guild Upgrade Configuration           #
#-----------------------------------------------------------#

# This section of the config will talk about various parts of upgrading a guild and allow you to choose how it works.
# For "mob-xp-multiplier" the default is 1, meaning that it will drop the normal amount of XP for non-upgraded guilds.
# DO NOT set it to 0, that will either throw errors or cause mobs to not drop XP.

# You can make as many as you want. You MUST name each tier "tier1, tier2, tier3, etc." while following the format of the already made ones.
# For example: if I wanted to add a 4th tier, I would do this:

# tier4:
#   name: "Diamond"
#   cost: 400
#   max-members: 100
#   mob-xp-multiplier: 4
#   damage-multiplier: 4
#   max-bank-balance: 40000
#   permissions:
#    - "example.permission.one"
#    - "example.permission.two"

# Keep in mind for the damage-multiplier, it applies to players also, so by default it's set to normal for every tier to allow you
# to choose how it will work.


max-number-of-tiers: 3
carry-over-perms: true

tier1:
  name: "Bronze"
  cost: 0
  max-members: 15
  mob-xp-multiplier: 1
  damage-multiplier: 1
  max-bank-balance: 10000
  members-to-rankup: 0
  permissions:
  -
tier2:
  name: "Silver"
  cost: 200
  max-members: 30
  mob-xp-multiplier: 2
  damage-multiplier: 1
  max-bank-balance: 20000
  members-to-rankup: 0
  permissions:
  -
tier3:
  name: "Gold"
  cost: 300
  max-members: 50
  mob-xp-multiplier: 3
  damage-multiplier: 1
  max-bank-balance: 30000
  members-to-rankup: 0
  permissions:
  -

#-----------------------------------------------------------#
#                     Guild Configuration                   #
#-----------------------------------------------------------#

# This section of the config will talk about various parts of making a guild and options as server owner you can set.

# The prefix of all messages send by this plugin to a player for all messages and commands
plugin-prefix: "[&b&lGuilds] "
# Would you like to display a user's displayname instead of their MC username?
tablist-use-display-name: false

# Change how the Prefixes in the TabList show!
# Note: DO NOT REMOVE THE {guild}
# You can use {prefix} to show the Guild Prefix instead if you would like.
tablist: "&7[&b{guild}&7]&r"

# Here you can modify how the /guild chat message style works.
guild-chat-format: "&7&l[Guild Chat]&r &b[{role}&b]&r &b {player}: {message}"
spy-chat-format: "&7&l[Guild Spy]&r &b[{guild}&b]&r &b[{role}&b]&r &b {player}: {message}"

# Change this to true if you want to allow players in the same guild / guild's that are allies with each other to damage each other.
allow-guild-damage: false
allow-ally-damage: false

# Check for update on startup (SUGGESTED YOU KEEP THIS ENABLED)
check-for-updates: true

name:
  # Minimum length of guild names
  min-length: 1
  # Maximum length of guild names
  max-length: 64
  # RegEx (https://en.wikipedia.org/wiki/Regular_expression) used to only allow certain characters (default only allows alphanumeric characters)
  # To turn off the ability for colored names change the regex to "^[a-zA-Z0-9]*$"
  regex: "^[a-zA-Z0-9&]*$"

# This will automatically prevent players from making a guild if it contains anything in the list below.
# Note: Capitalization doesn't matter. I can put "crap" and Crap cRaP, etc, will be blocked.
# Note: Also, it'll sense stuff such as "PieceofCrap", hopefully making it easier for you to make the blacklist.
enable-blacklist: true

blacklist:
- "crap"
- "ass"
- "stupid"

prefix:
  # With the default Regex currently set, the minimum length of the prefix is 1 and the maximum is 20.
  # To change this, adjust the numbers and maybe have a look at the link above (RegEx).
  # To turn off the ability for colored prefixes change the regex to "[a-zA-Z0-9]{1,20}"
  regex: "[a-zA-Z0-9&]{1,20}"
#-----------------------------------------------------------#
#                        Role Configuration                 #
#-----------------------------------------------------------#

roles:
  0:
    name: "GuildMaster"
    permission-node: "guilds.role.master"
    permissions:
      activate-buff: true
      add-ally: true
      ally-chat: true
      change-home: true
      change-prefix: true
      rename: true
      chat: true
      demote: true
      deposit-money: true
      invite: true
      kick: true
      open-vault: true
      promote: true
      remove-ally: true
      remove-guild: true
      toggle-guild: true
      transfer-guild: true
      upgrade-guild: true
      withdraw-money: true
      claim-land: true
      unclaim-land: true
      destroy: true
      place: true
      interact: true

  1:
    name: "Officer"
    permission-node: "guilds.role.officer"
    permissions:
      activate-buff: false
      add-ally: true
      ally-chat: true
      change-home: true
      change-prefix: false
      rename: false
      chat: true
      demote: true
      deposit-money: true
      invite: true
      kick: true
      open-vault: true
      promote: true
      remove-ally: true
      remove-guild: false
      toggle-guild: false
      transfer-guild: false
      upgrade-guild: false
      withdraw-money: true
      claim-land: false
      unclaim-land: false
      destroy: true
      place: true
      interact: true

  2:
    name: "Veteran"
    permission-node: "guilds.role.veteran"
    permissions:
      activate-buff: false
      add-ally: false
      ally-chat: true
      change-prefix: false
      rename: false
      chat: true
      demote: false
      deposit-money: true
      invite: true
      kick: false
      open-vault: true
      promote: false
      remove-ally: false
      remove-guild: false
      toggle-guild: false
      transfer-guild: false
      upgrade-guild: false
      withdraw-money: false
      claim-land: false
      unclaim-land: false
      destroy: true
      place: true
      interact: true
  3:
    name: "Member"
    permission-node: "guilds.role.member"
    permissions:
      activate-buff: false
      add-ally: false
      ally-chat: true
      change-prefix: false
      rename: false
      chat: true
      demote: false
      deposit-money: true
      invite: false
      kick: false
      open-vault: true
      promote: false
      remove-ally: false
      remove-guild: false
      toggle-guild: false
      transfer-guild: false
      upgrade-guild: false
      withdraw-money: false
      claim-land: false
      unclaim-land: false
      destroy: true
      place: true
      interact: true